### ISSUE TITLE
does not work on phones

### ISSUE THREAD

**Issue by alpha-gamer-pro** [MEEPofFaith/prog-mats-java-sonnicon#10]
i tried to download the mod but it always gives me a error that the mod can't be installed because it could not find the dex file path list pls make it compatible for some phones.

phone:galaxy s6 edge 
version:7.0.1(idk but i think it is like this i have to review it first)

**Comment by MEEPofFaith** [comment]
Java mods and some js mods don't work with android 7 and below.

**Comment by sk7725** [comment]
> Java mods and some js mods don't work with android 7 and below.

I think its 5, 6, 7- x and 3, 4, 8, 9~ o
Android 4 is reported to work and so is 8, 7 is not
~~like waht the fuc android~~
