### ISSUE TITLE
The Everything Gun broke the mod

### ISSUE THREAD

**Issue by Arthur-The-Ok** [MEEPofFaith/prog-mats-java-sonnicon#13]
According to the game, there is content error coming from the Everything Gun

File: prog-mats-java-everything-gun

[ClassCast]java.lang.String cannot be cast to entities.bullet.BulletType

**Comment by MEEPofFaith** [comment]
send me the whole crash report

**Comment by Arthur-The-Ok** [comment]
I don't know how to do it. I just reinstalled the mod, since it was
updated, opened the game and then a content error report showed up.

**Comment by MEEPofFaith** [comment]
well it ain't a crash so it's a minor thing I'll probably look at later.

**Comment by MEEPofFaith** [comment]
I don't have the same issue
