### ISSUE TITLE
suggestion: add anti air missile launcher

### ISSUE THREAD

**Issue by lokyinng** [MEEPofFaith/prog-mats-java-sonnicon#16]
all antiair missile launchers act like basic missile launchers but only target air and drop to the ground and damage the ground unit if run out of fuel
t1: shoot swarm missile using blast-compound
t2: same as basic missile launchers shoot anti air missile can be used with:
flak missile [missile that scatter into flak bullet]
point missile [shoot down missile projectile]
anti air missile [basic missile]

**Comment by MEEPofFaith** [comment]
What the fuck is fuel.

**Comment by SMOLKEYS** [comment]
xd
