### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Arthur-The-Ok** [MEEPofFaith/prog-mats-java-sonnicon#18]
![Captura de tela 2021-07-18 101921](https://user-images.githubusercontent.com/81048660/126068345-4c1c664f-cc97-4c73-b3dc-a4589066da8f.jpg)

**Comment by SMOLKEYS** [comment]
You can't really download it from the mod browser since meep might have messed it up.

How to download:

Go to `Releases`.

Open `Assets`.

Download `ProgMats.zipped.zip`

Unzip it.

Open Mindustry.

Open the `ProgMats.zipped` folder.

Import the file in the folder.

Done.
