### ISSUE TITLE
you should maybe consider a wiki

### ISSUE THREAD

**Issue by USMP-lancer** [MEEPofFaith/prog-mats-java-sonnicon#2]
cus yes

**Comment by MEEPofFaith** [comment]
~~how do i make one~~

**Comment by tezlm** [comment]
<@!409844605614424074>
![image](https://user-images.githubusercontent.com/56274831/113537777-6bb74680-958e-11eb-8b66-30cd65b749af.png)
![image](https://user-images.githubusercontent.com/56274831/113537811-85f12480-958e-11eb-8e09-7406b22a78ac.png)
![image](https://user-images.githubusercontent.com/56274831/113537841-9bfee500-958e-11eb-96b5-2f3e3d584f62.png)

**Comment by QmelZ** [comment]
> the asdasdasd wiki

10/10 wiki we need it for every mod

**Comment by MEEPofFaith** [comment]
hmm
*illl think about it, but for now imma sleep it's 3:10 am*

**Comment by USMP-lancer** [comment]
~~damn he has been thinking for about 11 days now~~

**Comment by MEEPofFaith** [comment]
~~I'm too lazy to bother~~

**Comment by USMP-lancer** [comment]
~~fair, also when you gonna release the payload based nukes?~~

**Comment by MEEPofFaith** [comment]
~~soon™~~

I guess I'll close this for now.
