### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Arthur-The-Ok** [MEEPofFaith/prog-mats-java-sonnicon#20]
![Captura de tela 2021-07-18 192645](https://user-images.githubusercontent.com/81048660/126083880-8eaa59a0-e0d5-4f2f-b6a0-d1fcd65c4323.jpg)
![Captura de tela 2021-07-18 192658](https://user-images.githubusercontent.com/81048660/126083885-e8f6049d-bea8-49e2-a046-e19846653412.jpg)
![Captura de tela 2021-07-18 192714](https://user-images.githubusercontent.com/81048660/126083889-3c7ffcbb-31c9-4779-908a-de514ef53e5c.jpg)
![Captura de tela 2021-07-18 192732](https://user-images.githubusercontent.com/81048660/126083891-c886da6e-1ac7-4ffd-84d9-d579b84d2260.jpg)
![Captura de tela 2021-07-18 192746](https://user-images.githubusercontent.com/81048660/126083894-5db19a9f-0d2f-4df8-bd80-e54fc5d2eecb.jpg)
![Captura de tela 2021-07-18 192802](https://user-images.githubusercontent.com/81048660/126083902-d11a1c3a-40ba-49ee-b40b-d408c029ebda.jpg)
![Captura de tela 2021-07-18 192815](https://user-images.githubusercontent.com/81048660/126083914-4a44d738-f213-4627-9c06-c5e6548f36d2.jpg)
![Captura de tela 2021-07-18 192828](https://user-images.githubusercontent.com/81048660/126083920-871a29f2-0746-4d18-b545-3db92ff1604c.jpg)
![Captura de tela 2021-07-18 192840](https://user-images.githubusercontent.com/81048660/126083923-8f1194bd-fc85-4573-ac35-ff4ef535c797.jpg)

**Comment by MEEPofFaith** [comment]
Don't use in v7, I haven't updated the code to work with it yet.
I am already aware of this.
