### ISSUE TITLE
Impossible Research Branch Due to Requiring Missile Shells Before You Can Craft Them

### ISSUE THREAD

**Issue by ridesdragons** [MEEPofFaith/prog-mats-java-sonnicon#25]
There seems to be an issue with the missile branch. I'm trying to research the Strikedown, but it requires Missile Shells. However, I cannot for the life of me find the Shell Press anywhere else on the tree. There is a node in the Overdrive branch that is a question mark, but it requires me to research the Strikedown in order to unlock it. Looking at the source code, it looks like it follows a similar tech branch scheme as the Tinker's branch (research the tinker, then the sentry crafter). If so, then that means that the Strikedown is impossible to research, due to needing something that it creates, breaking the entire branch.

**Comment by MrDuck557** [comment]
reading source code to verify

**Comment by MrDuck557** [comment]
Looks like it does that 
![image](https://user-images.githubusercontent.com/48808663/127551736-06b886da-3d4b-43a5-94e6-c92b46640e19.png)

**Comment by MEEPofFaith** [comment]
~~I haven't actually captured NPC yet so I've never been able to test wether it actually works or not~~

**Comment by MEEPofFaith** [comment]
~~Guess I have my answer now~~

**Comment by MEEPofFaith** [comment]
> There seems to be an issue with the missile branch. I'm trying to research the Strikedown, but it requires Missile Shells. However, I cannot for the life of me find the Shell Press anywhere else on the tree. There is a node in the Overdrive branch that is a question mark, but it requires me to research the Strikedown in order to unlock it. Looking at the source code, it looks like it follows a similar tech branch scheme as the Tinker's branch (research the tinker, then the sentry crafter). If so, then that means that the Strikedown is impossible to research, due to needing something that it creates, breaking the entire branch.

What version of Progressed Materials are you using? Can you send a screenshot of what shows when you hover over the Strikedown over the research menu?

**Comment by MEEPofFaith** [comment]
ah, I see

**Comment by MEEPofFaith** [comment]
Fixed
