### ISSUE TITLE
Factory Conveyor Ignoration

### ISSUE THREAD

**Issue by Hot-Sausage07** [MEEPofFaith/prog-mats-java-sonnicon#27]
Im not sure if mindustry is bugged or your mod is bugged
![image](https://user-images.githubusercontent.com/78838382/129001518-731c48f6-a942-419d-b2f6-f2bff169786d.png)
Although ya, it still put out items through the conveyor but
it conveyor ignores the factory

**Comment by MEEPofFaith** [comment]
That's an issue with `younggam/multi-lib` I guess.

I'm redoing everything for the next update anyways so I won't bother fixing this.
