### ISSUE TITLE
Controlling sword turrets crash the game

### ISSUE THREAD

**Issue by SMOLKEYS** [MEEPofFaith/prog-mats-java-sonnicon#4]
~~Everytime i try to build the new turrets my game instantly crashes~~

Whenever i try to control the new turrets my game crashes

**Comment by MEEPofFaith** [comment]
Does the new v1.1.1 release not fix this?

**Comment by SMOLKEYS** [comment]
> Does the new v1.1.1 release not fix this?

At 1.1, the turret crashes my game when i try to _build_ it.
At 1.1.1, the turret crashes my game when i try to _control_ it.

**Comment by SMOLKEYS** [comment]
Closed because everything is fine now.
